language: python

python:
  - "3.6"
  - "3.5"

# command to install dependencies
install:
  - pip install .

# command to run tests
script:
  - coverage run -m unittest discover test
  - coverage report -m
